#!/bin/bash

sudo yum update -y
sudo yum install -y docker procmail
sudo curl --silent --location https://rpm.nodesource.com/setup_7.x | sudo bash -
sudo yum install -y nodejs
cd /srv/quick-bench-back-end/
sudo service docker start
sudo useradd -M -s /sbin/nologin -r -G docker quick-bench
mkdir -m 777 -p $(printf "/data/%02x " $(seq 0 255))
sudo ./pull-docker
sudo cp quick-benchd /etc/init.d/.
sudo npm install
sudo ./seccomp.js
sudo sysctl -w kernel.perf_event_paranoid=1
sudo service quick-benchd start
